START_URL = 'https://www.charities.gov.sg/_layouts/MCYSCPSearch/MCYSCPSearchCriteriaPage.aspx'

CHARITIES_PER_PAGE = 5
MAX_RETRY_ATTEMPTS = 10

LAYOUT_PROFILE_MAPPING = {
    'name': '#ctl00_PlaceHolderMain_LabelOrgName',
    'uen': '#ctl00_PlaceHolderMain_lblUENNo',
}

LAYOUT_FINANCIAL_MAPPING = {
    'fy1': {
        'financial_period': '#ctl00_PlaceHolderMain_ucFSDetails_fy_period_2_0',
        'receipts_total': '#ctl00_PlaceHolderMain_ucFSDetails_income_total_2',
        'expenses_total': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_total_2',
        'receipts_donation_cash_tax_deductible': '#ctl00_PlaceHolderMain_ucFSDetails_income_td_cash_2',
        'receipts_donation_cash_non_tax_deductible': '#ctl00_PlaceHolderMain_ucFSDetails_income_ntd_cash_2',
        'receipts_donation_cash_total': '#ctl00_PlaceHolderMain_ucFSDetails_income_total_cash_2',
        'receipts_donation_kind_tax_deductible': '#ctl00_PlaceHolderMain_ucFSDetails_income_td_kind_2',
        'receipts_donation_kind_non_tax_deductible': '#ctl00_PlaceHolderMain_ucFSDetails_income_ntd_kind_2',
        'receipts_donation_kind_total': '#ctl00_PlaceHolderMain_ucFSDetails_income_total_kind_2',
        'receipts_government_grants': '#ctl00_PlaceHolderMain_ucFSDetails_income_gov_grants_2',
        'receipts_investment_income': '#ctl00_PlaceHolderMain_ucFSDetails_income_investment_2',
        'receipts_programme_fees': '#ctl00_PlaceHolderMain_ucFSDetails_income_program_fee_2',
        'receipts_others_income': '#ctl00_PlaceHolderMain_ucFSDetails_income_other_2',
        'capital_in_nature': '#ctl00_PlaceHolderMain_ucFSDetails_capital_in_nature_2',
        'expenses_fund_raising': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_fr_2',
        'expenses_charitable_local': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_cae_local_2',
        'expenses_charitable_overseas': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_cae_overseas_2',
        'expenses_charitable_total': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_total_cape_2',
        'expenses_others_total': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_other_2',
        'other_info_donation_other_charities': '#ctl00_PlaceHolderMain_ucFSDetails_oi_dgs_reg_charity_2',
        'other_info_no_of_employees': '#ctl00_PlaceHolderMain_ucFSDetails_oi_employee_no_2',
        'other_info_total_employee_costs': '#ctl00_PlaceHolderMain_ucFSDetails_oi_total_employee_cost_2',
        'other_info_fund_raising_efficiency_ratio': '#ctl00_PlaceHolderMain_ucFSDetails_oi_fr_efficiency_ratio_2',
        'other_info_total_related_party_transactions': '#ctl00_PlaceHolderMain_ucFSDetails_oi_total_related_party_2',
        'balance_assets_land_building': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_land_building_2',
        'balance_assets_other_tangible': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_other_tangible_2',
        'balance_assets_investments': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_investments_2',
        'balance_assets_inventories': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_inventories_2',
        'balance_assets_accounts_receivables': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_accounts_receivables_2',
        'balance_assets_cash_deposits': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_cash_deposits_2',
        'balance_assets_other_assets': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_other_2',
        'balance_assets_total': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_total_2',
        'balance_funds_unrestricted': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_unrestricted_2',
        'balance_funds_restricted': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_restricted_2',
        'balance_funds_endowment': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_endowment_2',
        'balance_funds_total': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_total_2',
        'balance_liabilities_current': '#ctl00_PlaceHolderMain_ucFSDetails_bs_liabilities_current_2',
        'balance_liabilities_non_current': '#ctl00_PlaceHolderMain_ucFSDetails_bs_liabilities_longterm_2',
        'balance_liabilities_total': '#ctl00_PlaceHolderMain_ucFSDetails_bs_liabilities_total_2',
        'balance_funds_liabilities_total': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_liabilities_total_2'
    },
    'fy2': {
        'financial_period': '#ctl00_PlaceHolderMain_ucFSDetails_fy_period_1_0',
        'receipts_total': '#ctl00_PlaceHolderMain_ucFSDetails_income_total_1',
        'expenses_total': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_total_1',
        'receipts_donation_cash_tax_deductible': '#ctl00_PlaceHolderMain_ucFSDetails_income_td_cash_1',
        'receipts_donation_cash_non_tax_deductible': '#ctl00_PlaceHolderMain_ucFSDetails_income_ntd_cash_1',
        'receipts_donation_cash_total': '#ctl00_PlaceHolderMain_ucFSDetails_income_total_cash_1',
        'receipts_donation_kind_tax_deductible': '#ctl00_PlaceHolderMain_ucFSDetails_income_td_kind_1',
        'receipts_donation_kind_non_tax_deductible': '#ctl00_PlaceHolderMain_ucFSDetails_income_ntd_kind_1',
        'receipts_donation_kind_total': '#ctl00_PlaceHolderMain_ucFSDetails_income_total_kind_1',
        'receipts_government_grants': '#ctl00_PlaceHolderMain_ucFSDetails_income_gov_grants_1',
        'receipts_investment_income': '#ctl00_PlaceHolderMain_ucFSDetails_income_investment_1',
        'receipts_programme_fees': '#ctl00_PlaceHolderMain_ucFSDetails_income_program_fee_1',
        'receipts_others_income': '#ctl00_PlaceHolderMain_ucFSDetails_income_other_1',
        'capital_in_nature': '#ctl00_PlaceHolderMain_ucFSDetails_capital_in_nature_1',
        'expenses_fund_raising': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_fr_1',
        'expenses_charitable_local': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_cae_local_1',
        'expenses_charitable_overseas': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_cae_overseas_1',
        'expenses_charitable_total': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_total_cape_1',
        'expenses_others_total': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_other_1',
        'other_info_donation_other_charities': '#ctl00_PlaceHolderMain_ucFSDetails_oi_dgs_reg_charity_1',
        'other_info_no_of_employees': '#ctl00_PlaceHolderMain_ucFSDetails_oi_employee_no_1',
        'other_info_total_employee_costs': '#ctl00_PlaceHolderMain_ucFSDetails_oi_total_employee_cost_1',
        'other_info_fund_raising_efficiency_ratio': '#ctl00_PlaceHolderMain_ucFSDetails_oi_fr_efficiency_ratio_1',
        'other_info_total_related_party_transactions': '#ctl00_PlaceHolderMain_ucFSDetails_oi_total_related_party_1',
        'balance_assets_land_building': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_land_building_1',
        'balance_assets_other_tangible': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_other_tangible_1',
        'balance_assets_investments': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_investments_1',
        'balance_assets_inventories': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_inventories_1',
        'balance_assets_accounts_receivables': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_accounts_receivables_1',
        'balance_assets_cash_deposits': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_cash_deposits_1',
        'balance_assets_other_assets': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_other_1',
        'balance_assets_total': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_total_1',
        'balance_funds_unrestricted': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_unrestricted_1',
        'balance_funds_restricted': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_restricted_1',
        'balance_funds_endowment': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_endowment_1',
        'balance_funds_total': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_total_1',
        'balance_liabilities_current': '#ctl00_PlaceHolderMain_ucFSDetails_bs_liabilities_current_1',
        'balance_liabilities_non_current': '#ctl00_PlaceHolderMain_ucFSDetails_bs_liabilities_longterm_1',
        'balance_liabilities_total': '#ctl00_PlaceHolderMain_ucFSDetails_bs_liabilities_total_1',
        'balance_funds_liabilities_total': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_liabilities_total_1'
    },
    'fy3': {
        'financial_period': '#ctl00_PlaceHolderMain_ucFSDetails_fy_period_0_0',
        'receipts_total': '#ctl00_PlaceHolderMain_ucFSDetails_income_total_0',
        'expenses_total': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_total_0',
        'receipts_donation_cash_tax_deductible': '#ctl00_PlaceHolderMain_ucFSDetails_income_td_cash_0',
        'receipts_donation_cash_non_tax_deductible': '#ctl00_PlaceHolderMain_ucFSDetails_income_ntd_cash_0',
        'receipts_donation_cash_total': '#ctl00_PlaceHolderMain_ucFSDetails_income_total_cash_0',
        'receipts_donation_kind_tax_deductible': '#ctl00_PlaceHolderMain_ucFSDetails_income_td_kind_0',
        'receipts_donation_kind_non_tax_deductible': '#ctl00_PlaceHolderMain_ucFSDetails_income_ntd_kind_0',
        'receipts_donation_kind_total': '#ctl00_PlaceHolderMain_ucFSDetails_income_total_kind_0',
        'receipts_government_grants': '#ctl00_PlaceHolderMain_ucFSDetails_income_gov_grants_0',
        'receipts_investment_income': '#ctl00_PlaceHolderMain_ucFSDetails_income_investment_0',
        'receipts_programme_fees': '#ctl00_PlaceHolderMain_ucFSDetails_income_program_fee_0',
        'receipts_others_income': '#ctl00_PlaceHolderMain_ucFSDetails_income_other_0',
        'capital_in_nature': '#ctl00_PlaceHolderMain_ucFSDetails_capital_in_nature_0',
        'expenses_fund_raising': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_fr_0',
        'expenses_charitable_local': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_cae_local_0',
        'expenses_charitable_overseas': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_cae_overseas_0',
        'expenses_charitable_total': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_total_cape_0',
        'expenses_others_total': '#ctl00_PlaceHolderMain_ucFSDetails_expenses_other_0',
        'other_info_donation_other_charities': '#ctl00_PlaceHolderMain_ucFSDetails_oi_dgs_reg_charity_0',
        'other_info_no_of_employees': '#ctl00_PlaceHolderMain_ucFSDetails_oi_employee_no_0',
        'other_info_total_employee_costs': '#ctl00_PlaceHolderMain_ucFSDetails_oi_total_employee_cost_0',
        'other_info_fund_raising_efficiency_ratio': '#ctl00_PlaceHolderMain_ucFSDetails_oi_fr_efficiency_ratio_0',
        'other_info_total_related_party_transactions': '#ctl00_PlaceHolderMain_ucFSDetails_oi_total_related_party_0',
        'balance_assets_land_building': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_land_building_0',
        'balance_assets_other_tangible': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_other_tangible_0',
        'balance_assets_investments': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_investments_0',
        'balance_assets_inventories': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_inventories_0',
        'balance_assets_accounts_receivables': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_accounts_receivables_0',
        'balance_assets_cash_deposits': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_cash_deposits_0',
        'balance_assets_other_assets': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_other_0',
        'balance_assets_total': '#ctl00_PlaceHolderMain_ucFSDetails_bs_assets_total_0',
        'balance_funds_unrestricted': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_unrestricted_0',
        'balance_funds_restricted': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_restricted_0',
        'balance_funds_endowment': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_endowment_0',
        'balance_funds_total': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_total_0',
        'balance_liabilities_current': '#ctl00_PlaceHolderMain_ucFSDetails_bs_liabilities_current_0',
        'balance_liabilities_non_current': '#ctl00_PlaceHolderMain_ucFSDetails_bs_liabilities_longterm_0',
        'balance_liabilities_total': '#ctl00_PlaceHolderMain_ucFSDetails_bs_liabilities_total_0',
        'balance_funds_liabilities_total': '#ctl00_PlaceHolderMain_ucFSDetails_bs_funds_liabilities_total_0'
    }
}